---
name: build and push

on:
  schedule:
    - cron: '0 11 * * 2'
  workflow_dispatch:

jobs:
  docker:
    name: build and push docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
        - {
          compiler-variant: "GCC12_NoMPI",
          compiler-variant-image: ubuntu:22.04
        }
        - {
          compiler-variant: "GCC12_MPICH",
          compiler-variant-image: ubuntu:22.04
        }
        - {
          compiler-variant: "IntelOneAPI_NoMPI",
          compiler-variant-image: intel/oneapi:2024.2.0-1-devel-ubuntu22.04
        }
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Gather metadata (test layer)
        id: meta-test
        uses: docker/metadata-action@v5
        with:
          images: |
            shivupa/cclib-ci
          flavor: |
            latest=true
          tags: |
            type=sha,prefix=${{ matrix.config.compiler-variant }}-test-
      -
        name: Gather metadata (CI layer)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            shivupa/cq-ci
          flavor: |
            latest=true
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}},prefix=${{ matrix.config.compiler-variant }}-
            type=sha,prefix=${{ matrix.config.compiler-variant }}-
            type=edge,prefix=${{ matrix.config.compiler-variant }}-
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and export to Docker (test layer)
        uses: docker/build-push-action@v5
        with:
          build-args: |
            COMPILER_VARIANT_IMAGE=${{ matrix.config.compiler-variant-image }}
          push: false
          load: true
          tags: ${{ steps.meta-test.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: test
      -
        name: Build and export to Docker (CI layer)
        uses: docker/build-push-action@v5
        with:
          build-args: |
            COMPILER_VARIANT_IMAGE=${{ matrix.config.compiler-variant-image }}
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ci
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ github.event_name != 'pull_request'}}
      -
        name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          build-args: |
            COMPILER_VARIANT_IMAGE=${{ matrix.config.compiler-variant-image }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
        if: ${{ github.event_name != 'pull_request'}}
